Add Room interface & classes
narussiafund/Just-For-Today pull request #15
Opened 2020-10-21 15:49 UTC by ArthurNNN

2020-10-21 16:49 UTC, narussiafund requested changes

2020-10-21 16:49 UTC, narussiafund commented on app/src/main/java/org/narussia/justfortoday/data/Dairy.kt
>      var date: String = ""
Если по умолчанию будет пустая строка PrimaryKey, то есть вероятность, что приложение крашнется. Надо или от пустой строки избавиться или добавить свою ключ Int c @PrimaryKey(autoGenerate = true) Но тут будет вероятность того, что  данные могут задвоиться.

2020-10-21 16:49 UTC, narussiafund commented on app/src/main/java/org/narussia/justfortoday/data/local/DairyDatabase.kt
> +    abstract fun DairyDao(): DairyDao
Функция с большой буквы

2020-10-21 16:49 UTC, narussiafund commented on app/src/main/java/org/narussia/justfortoday/data/local/DairyDatabase.kt
> +        var INSTANCE: DairyDatabase? = null
Надо сделать приватной переменную и добавить @Volatile

2020-10-21 16:49 UTC, narussiafund commented on app/src/main/java/org/narussia/justfortoday/data/local/DairyDao.kt
> +    fun getDairyByDate(date: String): Dairy
Эта функция должна вернуть LiveData<Dairy>

2020-10-24 15:59 UTC, ArthurNNN commented on app/src/main/java/org/narussia/justfortoday/data/Dairy.kt
>      var date: String = ""
может сегодняшней датой проинициализировать?

2020-10-24 16:00 UTC, ArthurNNN commented on app/src/main/java/org/narussia/justfortoday/data/Dairy.kt
>      var date: String = ""
второй вариант c autogenerate:
@Entity
class Dairy {
    @PrimaryKey @ColumnInfo(name = "entryid") var id: String = UUID.randomUUID().toString()
    @ColumnInfo(name = "date") var date: String = ""
    @ColumnInfo(name = "day") var  day = 0
    @ColumnInfo(name = "month") var  month = 0
    @ColumnInfo(name = "title") var  title: String = ""
    @ColumnInfo(name = "basetext") var  basetext: String = ""
    @ColumnInfo(name = "daytext") var  daytext: String = ""
    @ColumnInfo(name = "justfortoday") var  justfortoday: String = ""
}

2020-10-24 16:51 UTC, closed without merging